"""roffle table

Revision ID: 0d75e1e4aa4c
Revises: cd1a7ef78fe3
Create Date: 2022-08-16 15:59:57.624363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d75e1e4aa4c'
down_revision = 'cd1a7ef78fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roffle', sa.Column('fifa_skill', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roffle', 'fifa_skill')
    # ### end Alembic commands ###
