"""roffle table

Revision ID: b594f0228061
Revises: 0d75e1e4aa4c
Create Date: 2022-08-16 16:55:27.994516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b594f0228061'
down_revision = '0d75e1e4aa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fellas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fella_name', sa.String(length=140), nullable=True),
    sa.Column('fella_location', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fellas')
    # ### end Alembic commands ###
