"""roffle table

Revision ID: cd1a7ef78fe3
Revises: 0dc44e84f35a
Create Date: 2022-08-16 15:57:45.898109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1a7ef78fe3'
down_revision = '0dc44e84f35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roffle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fifa_name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roffle')
    # ### end Alembic commands ###
